GET localhost:5235/todo-items

###

POST localhost:5235/todo-items
Content-Type: application/json

{
    "id": "123",
    "name": "todo1",
    "details": "todo1 description"
}

###


PUT localhost:5235/todo-items/123
Content-Type: application/json

{
    "id": "123",
    "name": "todo1",
    "details": "todo1 description",
    "completed": true
}
